### ISSUE TITLE
nc-hammer block when netconf server close session

### ISSUE THREAD

**Issue by chunlovemail** [damianoneill/nc-hammer#20]
### Things try first
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest nc-hammer master branch?

### Description
There's some probability that nc-hammer will block when communicate with netopeer2-server.
The position is `WaitForFunc` in the file `vendor/github.com/Juniper/go-netconf/netconf/transport.go`

### Steps to Reproduce
1. Write yml, set iterations=100, clients=1, reuseconnection=true, netconf actions number=2. Please find the `get.yml.txt`attachment.
2. run command `./nc-hammer run get.yml`
3. Then nc-hammer will block with some probability and can not exit until user input `<ctrl+c>`
   `..eeeeeeeeeeeeee..eeeeeeeeeeeeeee..eee^C`
4. Run a new nc-hammer, the communication is OK.

### Versions
branch: master
commit f06c0ef7abb2137ba80c43f7598b6914ea65eb8d

### Netopeer2-server Log
We can see that netopeer2-server write reply failed, then it close the session.
```
`Accept session 1.
Accept session 2.
Session 2: SSH channel write failed, strerror: Success
Session 2: communication socket unexpectedly closed.
Session 2: failed to write reply.
Session 2: thread 1 event session terminated.
Accept session 3.
Accept session 4.
Session 4: SSH channel write failed, strerror: Success
Session 4: communication socket unexpectedly closed.
Session 4: failed to write reply.
Session 4: thread 1 event session terminated.
Accept session 5.
Accept session 6.
Session 6: SSH channel write failed, strerror: Success
Session 6: communication socket unexpectedly closed.
Session 6: failed to write reply.
Session 6: thread 14 event session terminated.
Session 1: inactive read timeout elapsed.
Session 1: thread 0 event session terminated.
Session 3: inactive read timeout elapsed.
Session 3: thread 12 event session terminated.
Session 5: inactive read timeout elapsed.
Session 5: thread 1 event session terminated.`
```

### nc-hammer Log
1.I had add some note in `"vendor/github.com/Juniper/go-netconf/netconf/transport.go"`. The log show that nc-hammer has been block by `t.Read`. 
2.It seems that nc-hammer waits to read reply from netopeer2-server. But the notopeer2-server had closed the socket, so nc-hammer been waiting here. (without timeout?)
```
func (t *transportBasicIO) WaitForFunc(f func([]byte) (int, error)) ([]byte, error) {
	var out bytes.Buffer
	buf := make([]byte, 4096)

	pos := 0
	for {
		fmt.Printf("+") //Add
		n, err := t.Read(buf[pos : pos+(len(buf)/2)])
		fmt.Printf("-") //Add
```

### Attachment
(Github not support yml format T_T)
[get.yml.txt](https://github.com/damianoneill/nc-hammer/files/2266130/get.yml.txt)

### More test
1.Only modify `reuseconnection` to false, the communication is OK
2.Only modify `netconf actions` number to 1, the communication is OK

Thanks!

**Comment by damianoneill** [comment]
@chunlovemail thanks for the issue req.  

Why is the netopeer-2 write reply failing, is this expected behaviour?  Can this be resolved?  I assume the correct behaviour is that when the client creates a connection, this should remain open indefinitely, ideally until it closed by the client.

I will raise an issue with the go-netconf library and refer back to this as input.

**Comment by chunlovemail** [comment]
Hi Damian,
   Thanks for your support.  
   Now, I can only see that netopeer2-server call `ssh_channel_write` failed. I will check the netopeer2-server code for more information.

Thanks!
